fix(wc1): Fix tokens, variables, styles
emulsify-ds/emulsify-web-components pull request #1
Opened 2023-11-06 17:09 UTC by mariannuar

## Summary

This PR fixes the following 

- Way of usen tokens/variables in some components
- Styles

## How to review this pull request
- [ ] Run `npm run develop`
- [ ] Check all the current stories look good
- [ ] Ensure

2023-11-13 15:03 UTC, mcortes19 requested changes
@mariannuar left a comment related to a console.log I found, other than that everything looks good to me!

2023-11-13 15:03 UTC, mcortes19 commented on src/components/tokens/color-tokens/color-tokens.ts
> +        console.log(Object.entries(data));
@mariannuar please get rid of this `console.log`

2023-11-13 21:45 UTC, mariannuar commented
@mcortes19 Done. Thank you!

2023-11-16 22:11 UTC, mcortes19 approved these changes
@mariannuar LGTM 🎖️

2023-11-17 15:54 UTC, merged