Accordion component
emulsify-ds/emulsify-web-components pull request #2
Opened 2023-11-13 16:58 UTC by robherba

## Summary

Adds an accordion component.

## How to review this pull request

- [ ] Run `npm run develop`
- [ ] Go to the accordion component page: [/story/components-accordion](http://localhost:6006/?path=/story/components-accordion--accordion)
- [ ] Feel free to comment, suggest changes or improvements.

<img width="1512" alt="image" src="https://github.com/emulsify-ds/emulsify-web-components/assets/9342274/6bfc5317-b518-40af-863d-ef8631c39489">

2023-11-17 16:14 UTC, mariannuar requested changes
I think there are some things missing from the `Accordion` that is on Emulsify UI Kit. Can you please compare this component with the one on UI Kit, and check that nothing is missing, at least in styles.

2023-11-17 16:14 UTC, mariannuar commented on src/components/accordion/accordion.stories.ts
> +  component: 'ewc-accordion',
Please, change it to `emulsify-accordion`

2023-11-17 16:14 UTC, mariannuar commented on src/components/accordion/accordion.ts
> +@customElement('ewc-accordion')
Please, change it to `emulsify-accordion`

2023-11-17 16:14 UTC, mariannuar commented on src/components/accordion/accordion.ts
> +      background-color: var(--color-grays-100);
```suggestion
      background-color: var(--accordion-color-header-hover);
```

2023-11-17 16:14 UTC, mariannuar commented on src/components/accordion/accordion.ts
> +      border-bottom: 1px solid var(--color-grays-100);
```suggestion
      border-bottom: 1px solid var(--accordion-divider-color);
      padding-top: var(--spacing-lg);
```

2023-12-05 17:28 UTC, mariannuar reviewed
This looks and works as good. There are still some things that we need to add, for example, the 'Inter' typography and use the `icon` component. Let's wait to have that component merged, to include to this one :)

2023-12-14 14:09 UTC, cienvaras approved these changes

2023-12-14 14:09 UTC, merged